name: Create Pull Request
on:
  push:
    branches:
      - 'ready/*'

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          node-version: 'ref' # Specify Node.js version 16

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          title: 'Create Pull Request'
          body: 'This pull request was automatically created when the "ready/" branch was pushed.'
          node-version: 'ref' # Specify Node.js version 16 for this action as well
