name: Create Pull Request
on:
  push:
    branches:
      - 'ready/*' # Define the branch pattern to trigger the workflow

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'main'
          title: 'Create Pull Request'
          body: 'This pull request was automatically created when the "ready/" branch was pushed.'
