name: Pull Request Action
on:
  push:
    branches:
      - ready/*

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "2.0.0"
          github_token: ${{ secrets.GITHUB_TOKEN }}