name: Java CI with Maven and Auto PR

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
      - name: Build with Maven
        run: mvn -B package --file pom.xml

  create_pull_request:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get branch name from push event
        id: branch_name
        run: echo "::set-output name=branch::$(echo $GITHUB_REF | awk -F/ '{print $3}')"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Automatic PR from ${{ steps.branch_name.outputs.branch }}
          branch: main
          body: This pull request was automatically created when pushing to the main branch.
